### ISSUE TITLE
Support parsing slim (or temple?) template files

### ISSUE THREAD

**Issue by oboxodo** [Shopify/packwerk#142]
It'd be nice to be able to include [slim](http://slim-lang.com/) files, just like erb files are supported. Slim is actually built on top of [Temple](https://github.com/judofyr/temple#engines-using-temple) which is a generic templates parser/compiler. Maybe it would even be worth it to replace the existing erb parser with a temple parse as it includes erb built-in and you'd be getting support for many others all at once.

**Comment by exterm** [comment]
It's far from being decided, but Shopify has been replacing lots of `erb` with react frontends, so the question came up whether we should remove the `erb` parser. It won't happen any time soon though.

**Comment by mclark** [comment]
> Do I understand correctly that you're interested in continued erb support, Matt?

Yes, for the foreseeable future at least GitHub is still using erb files and will need these constants to be detected.

**Comment by exterm** [comment]
Thank you for chiming in! Will keep that in mind if the topic comes up again.

**Comment by rafaelfranca** [comment]
Closing since we don't have any interest on adding more parsers for packwerk. We are open to receive PRs making it easier to plugin different parsers if available though.
