### ISSUE TITLE
Privacy violations in migrations

### ISSUE THREAD

**Issue by wildmaples** [Shopify/packwerk#16]
## Problem

Privacy violations in migrations seem to be caught by Packwerk. 

![image](https://user-images.githubusercontent.com/25471753/87701197-9134c380-c765-11ea-9379-eb8cb7a7f93a.png)

![image](https://user-images.githubusercontent.com/25471753/87701212-972aa480-c765-11ea-9573-fc1afc5a82e1.png)

We suspect the `t.belongs_to(:order)` is what is setting off the violation, as Packwerk thinks it is an active record association. 

To get rid of these type of violations, users have been putting this violation in to the `deprecated_references.yml` list.

## Potential solutions 
There may be two solutions: 
1. change the associations inspector to ignore methods that are not called on an implicit self
2. ignore violations in migrations files

**Comment by exterm** [comment]
We've opted to ignore migration files for now. Let's see if this problem comes up again.
