### ISSUE TITLE
Add unit tests for ApplicationValidator checks

### ISSUE THREAD

**Issue by wildmaples** [Shopify/packwerk#17]
We have `ApplicationValidatorTest` which are integration tests. However, we should find a way to unit test the individual checks. 

We could make unit testing this file easier by refactoring it so a fake filesystem can be injected. 
This would make it easier to test but would require a larger refactor. https://github.com/Shopify/packwerk-old/pull/262#discussion_r455956863

TO DO:

- [ ] check_autoload_path_cache,
- [ ] check_package_manifests_for_privacy,
- [ ] check_package_manifest_syntax,
- [ ] check_application_structure,
- [ ] check_inflection_file,
- [ ] check_acyclic_graph,
- [ ] check_package_manifest_paths,
- [ ] check_valid_package_dependencies,
- [ ] check_root_package_exist,

**Comment by rochlefebvre** [comment]
Addressed in #84
