### ISSUE TITLE
Declare a specific constant as a Dependency

### ISSUE THREAD

**Issue by burkematthew** [Shopify/packwerk#191]
**Description**
I am relatively new to Packwerk and working on building out different modularized portions of our application.  As I am slowly chipping away at the backlog of packages needed, there are a lot of dependencies from the original structure of our application.  

For example, I am building out a package that references a specific Model in the original `app/models` location.  

Package:
- File path: `app/packages/home_operations`
- Specific class in question: `app/packages/home_operations/services/cleaning.rb`

Constant:
- File path: 'app/models/job.rb`
- Constant: `::Job`

**Expected Behaviour**
Instead of declaring the entire package or an entire directory, I'd like to be able to simply say `::Job` is a dependency, creating a much more concise dependency declaration.

**Version Information**
 - Packwerk: 2.1.1
 - Ruby: 3.0
 - Rails: 6.1.5

**Additional Context**
When running `packwerk update-deprecations`, this is the output added to my `deprecated-references.yml`:

```
".":
  "::Job":
    violations:
    - dependency
    files:
    - app/packages/home_operations/services/cleaning.rb
```

I don't see anything in the documentation\USAGE.md that would seem to point to the expected formatting of the `dependencies` entry in `package.yml`.

Any guidance would be greatly appreciated!

**Comment by exterm** [comment]
You could create a package that only contains `::Job`.

**Comment by burkematthew** [comment]
@exterm thanks for the reply! I figured as much but thought I'd at least reach out and see if I was missing something. I appreciate the suggestions.
