### ISSUE TITLE
Automate the adding of new package file paths to the config file

### ISSUE THREAD

**Issue by wildmaples** [Shopify/packwerk#20]
We want to automate the process of adding new filepaths from packages in `.rubocop.packages.yml` config file. This process could be done when `update` command is ran. 

![image](https://user-images.githubusercontent.com/25471753/78590175-6acec600-780f-11ea-9e64-adaa05084d5c.png)

**Comment by AlexEvanczuk** [comment]
I think we can close this issue now @exterm with Packwerk 2.0

**Comment by exterm** [comment]
👍🏼
