### ISSUE TITLE
Refactor how node processing work

### ISSUE THREAD

**Issue by wildmaples** [Shopify/packwerk#22]
We would like to refactor how updating the shitlist work. 

https://github.com/Shopify/packwerk-old/pull/181#pullrequestreview-417116089

Base of @thegedge's suggestion we have at least two options to explore:
 
1) Change the behaviour of `RunContext`, and we returned a different node processor for updating versus checking. 

2) File and node processor work together to yield references, and some other class (e.g., Cli) would then process the references differently based on whether we're checking or updating

**Comment by mclark** [comment]
@rafaelfranca I think this might be closed based on my work for parallelization?
