### ISSUE TITLE
[Bug Report] Incompatibility with latest `zeitwerk` version (2.6.4) - undefined method `root_dirs`

### ISSUE THREAD

**Issue by iMacTia** [Shopify/packwerk#253]
**Description**
`packwerk` breaks with latest `zeitwerk` fix version (2.6.4).
This is because a method considered private (root_dirs) was renamed, but it's being used by `packwerk`.
See [this commit](https://github.com/fxn/zeitwerk/commit/af1d6ac6ec687aacb361bcdd71edf304b7ce6ad8) for more details.

**To Reproduce**
Update `zeitwerk` to v2.6.4 and run `packwerk check` or `packwerk validate`.

**Expected Behaviour**
The `packwerk` command should succeed.

**Version Information**
 - Packwerk: 2.2.1
 - Ruby 3.1

**Comment by alexevanczuk** [comment]
Thanks for the report 🙏 @jeffmeyers is on it! https://github.com/Shopify/packwerk/pull/251

**Comment by alexevanczuk** [comment]
@carlost and other folks who emoji reacted (@benrbrook, @ericfirth, @iMacTia)

You can find the fix in this release:
https://github.com/Shopify/packwerk/releases/tag/v2.2.2
