### ISSUE TITLE
[Packwerk 3.0] Update UPGRADING.md with directions to upgrade to 3.0

### ISSUE THREAD

**Issue by alexevanczuk** [Shopify/packwerk#273]
Let's make sure folks have an easy path to migration. We might consider baking some of the upgrade capabilities into packwerk itself, such as automated commands to migrate `deprecated_references.yml` to `package_todo.yml`.

Here are a list of things to include:
- migrating to `package_todo.yml`
- requiring the extracted privacy checker from `packwerk-extensions`.
- if you were using methods like `Packwerk::Package#enforce_privacy?`, you'll want to use API available in `packwerk-extensions`
- updating user docs to reference `bin/packwerk update-todo` rather than `bin/packwerk update-deprecations`
- Removal of `bin/packwerk detect-stale-violations`, which is now replaced with `bin/packwerk check`

**Comment by gmcgibbon** [comment]
I'll add some quick docs for the behaviour of deleting `deprecated_references.yml` automatically and reference your gem for those who still want privacy checks. Thank you for reminding me with the milestone. ❤️
