### ISSUE TITLE
Packwerk thinks that `app/helpers/foobar_fizz.rb` is in the package `app/helpers/foobar` and not `app/helpers`

### ISSUE THREAD

**Issue by andrewhamon** [Shopify/packwerk#297]
**Description**
When a file has a prefix that matches an adjacent folder with a package in that folder, Packwerk thinks that the file belongs to the wrong package.

Directory layout:

```
app/helpers
├── package.yml
├── foobar_fizz.rb     # class FoobarFizz, depends on Meow::Woof. NOT part of the app/helpers/foobar package
├── foobar
│   ├── package.yml
│   └── subclass.rb    # class Foobar::Subclass
└── meow
    ├── package.yml
    └── woof.rb        # class Meow::Woof

```

`foobar_fizz.rb` is in the directory/package `app/helpers`. It depends on the package `app/helpers/meow`. Packwerk wants that dependency declared in `app/helpers/foobar` rather than `app/helpers`.

**To Reproduce**
Minimal reproduction: https://github.com/andrewhamon/packwerk-reproduction#readme

In the repo, run:
```
bundle install
bundle exec packwerk check
```

**Expected Behaviour**
There should be no error, as the dependency was declared in the correct package. If the package `app/helpers/foobar` (which is uninvolved) is removed, the errors go away, which is very surprising.

**Version Information**
 - Packwerk: 2.2.2
 - Ruby: 3.1.2

**Comment by exterm** [comment]
yeah it is this https://github.com/Shopify/packwerk/blob/f52fb63cb42336e6b470c9079041b1e56e7b4775/lib/packwerk/package.rb#L45
