### ISSUE TITLE
Packwerk can't parse `self::`

### ISSUE THREAD

**Issue by ngan** [Shopify/packwerk#31]
**Description**
Packwerk can't parse a this file:
```ruby
class Foobar
  self::SOMETHING = 'foo'
end
```

**To Reproduce**
Create a ruby file with the contents above and have Packwerk check it.

**Expected Behaviour**
Not error

**Version Information**
 - Packwerk: [v1.0.0]
 - Ruby [v1.7]

**Comment by ngan** [comment]
The example I gave was boiled down from an spec file in our code base. It looks something like this:
```ruby
RSpec.shared_examples_for 'a mailer' do
  describe 'mail basics' do
    self::SOMETHING = { include: :to, exclude: :not_to }.freeze
```

I _think_ we can "throw out" all `self` references? Since they would just resolve to whatever the containing class is and that class would declared elsewhere? So maybe the solution to this is:

1. Add `SELF = :self` to here: https://github.com/Shopify/packwerk/blob/main/lib/packwerk/node.rb#L18
2. Ignore it here: https://github.com/Shopify/packwerk/blob/main/lib/packwerk/node.rb#L40-L41

**Comment by jcw-** [comment]
@ngan FYIW, I encountered this same issue, made your suggested changes, and I got past them - willing to try and a branch if you want some help QA'ing a PR... :)

**Comment by exterm** [comment]
This should be fixed with https://github.com/Shopify/packwerk/pull/54, right @ngan ?

**Comment by ngan** [comment]
Yup!
