### ISSUE TITLE
Create flag for buildkite parallelism for `packwerk check` 

### ISSUE THREAD

**Issue by wildmaples** [Shopify/packwerk#5]
Make `packwerk` compatible with buildkite parallelism. We could add a `--parallelism_count` and `--parallelism_index` (or some other names) and have buildkite set up to pass the env vars into those flags. This means no need to create another binstub for CI, and also means we can work with any CI system.

**Comment by rafaelfranca** [comment]
Packwerk now runs in parallel by default using all available CPUs
